[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "argus_inference_service"
version = "0.1.0"
# Because your code is just app.py at top level:
py_modules = ["app"]
