name: ci

on:
  push:
    branches: [ main ]
  pull_request:   
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you use Poetry: pip install poetry && poetry install --no-interaction
          pip install -r requirements.txt
          pip install -r requirements-dev.txt   # pytest, coverage, etc.

      - name: Show repo tree
        run: |
          pwd
          find . -maxdepth 2 -type f -name '*.py'
        
      # - name: Run tests
      #   run: pytest 
        
    