name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt   # coverage, httpx, etc.

      - name: Run unit tests with coverage
        run: |
          # Run the suite and collect coverage
          coverage run -m unittest discover -s tests -p 'test_*.py'
          # Create coverage.xml so other steps/services can parse it
          coverage xml
